### ISSUE TITLE
Cannot connect with websocket deepstream 

### ISSUE THREAD

**Issue by gperezalba** [Alethio/ethstats-network-server#13]
Hi guys,

I have a private network running in AWS instances. I have a https://subdomain to which is redirected to ip:port of the dashboard. I have another https://subdomain to connect to deepstream. I start ethstats with docker/lite-mode/memory-persistence docker-compose up. My docker-compose.yml is:
`version: '3.3'
services:
  server:
    container_name: ethstats-network-server
    image: alethio/ethstats-network-server:latest
    restart: always
    depends_on:
      - deepstream
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3030:3030
      - 127.0.0.1:8888:8888
    environment:
      - NETWORK_ID=89
      - NETWORK_NAME=testnet
      - LITE=1
      - LITE_DB_PERSIST=0
      - LITE_API_PORT=3030
      - APP_PORT=3000
      - METRICS_PORT=8888
      - DEEPSTREAM_HOST=ds.domain.io
      - DEEPSTREAM_ORIGIN=https://ethstats.domain.io
    command: ["./bin/app.js", "-v"]
  deepstream:
    container_name: ethstats-network-deepstream
    image: deepstreamio/deepstream.io:latest
    restart: always
    ports:
      - ip:6020:6020
  dashboard:
    container_name: ethstats-network-dashboard
    image: alethio/ethstats-network-dashboard:latest
    restart: always
    depends_on:
      - server
    volumes:
      - ../../config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - ip:8082:80
    environment:
      - NETSTATS_API_URL=http://127.0.0.1:3030
      - DS_URL=wss://ds.domain.io
      - DS_USER=frontend
      - DS_PASS=`

In the browser I got: `failed: Error during WebSocket handshake: Unexpected response code: 408`
I'm not sure if env variable `DEEPSTREAM_ORIGIN` can be used or if I'm using it properly...

Thanks in advance

Guillermo

**Comment by baxy** [comment]
Hi Guillermo,

The `DEEPSTREAM_ORIGIN` env var is not supported. But from what I see you tried to redirect deepstream to a subdomain on the `https` protocol. I think your problem is because you need to support the wss protocol instead. Also try to specify the protocol explicitly like `DEEPSTREAM_HOST=wss://ds.domain.io`.

Thanks for your feedback.

**Comment by gperezalba** [comment]
Hi @baxy 

Yes that was the problem. As wss uses the same port as https I thought it could work but it needs wss. It is working now!

Thanks
