### ISSUE TITLE
What's the difference between the Lite mode and Cluster mode?

### ISSUE THREAD

**Issue by NeverKnowsTomorrow** [Alethio/ethstats-network-server#16]
Hi, i have run a private network with 6 nodes, and i want to monitor the state of all nodes . I have run the Lite mode on one of the 6 nodes with docker, but it seems that only the local node that deployed ethstats-network-server can register successfully. When i try to run and register to the server with ethstats-cli on another node , it doesn't work.

Is it necessary to run the cluster mode to monitor all nodes? And how to run a cluster mode? The README file seems no detailed description. Can I run `docker-compose up` in the `ethstats-network-server/docker/cluster-mode/postgres-persistence` ?

Thanks~

**Comment by NeverKnowsTomorrow** [comment]
Update: 

I have solved this problem, just set the server IP of  `docker-compose.yml` to public IP address, like that:
```yml
ports:
   - 123.123.123.123:3000:3000
```
The lite mode also can monitor all nodes in private network.

Another question:

How can I use IPv6 address in docker to provide the server service?

**Comment by baxy** [comment]
Hi,

It's not necessary to install in cluster mode to monitor all nodes. The cluster setup is designed for high availability, high throughput and large storage for the data collected from the nodes. In order for the other clients to see the server you'll need to configure the network accordingly.

Indeed, you can also run docker-compose up on the cluster sample file with the mention that all those services listed in there needs a server with proper resources.

Regarding docker and IPv6 you need to set it up to support it. https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/

Hope this helps

**Comment by NeverKnowsTomorrow** [comment]
> Hi,
> 
> It's not necessary to install in cluster mode to monitor all nodes. The cluster setup is designed for high availability, high throughput and large storage for the data collected from the nodes. In order for the other clients to see the server you'll need to configure the network accordingly.
> 
> Indeed, you can also run docker-compose up on the cluster sample file with the mention that all those services listed in there needs a server with proper resources.
> 
> Regarding docker and IPv6 you need to set it up to support it. https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/
> 
> Hope this helps

Thanks for your help!
