### ISSUE TITLE
No data is shown in Alethio dashboard

### ISSUE THREAD

**Issue by mohjam2004** [Alethio/ethstats-network-server#23]
Hi, @baxy 
I have deployed besu on kubernetes based on this doc: https://github.com/ConsenSys/quorum-kubernetes/tree/master/kubectl/quorum-besu/ibft2
everything works fine and I can execute smart contracts successfully on it through json-rpc.
I have deployed Alethio block explorer on kubernetes cluster and connect it to besu node so I can see blocks and transactions in block explorer.
![image](https://user-images.githubusercontent.com/59224403/115885811-8b42e000-a465-11eb-9635-43e37d19a614.png)

I have run Alethio ethstat (server-dashboard-stream) based on docker compose on a node outside kubernetes cluster from which I manage my cluster and edit docker compose file to fit my deployed besu.
this is docker compose yaml file:

version: '3.7'
services:
  server:

    container_name: ethstats-network-server
    image: alethio/ethstats-network-server:latest
    restart: always
    depends_on:
      - deepstream
    ports:
      - 0.0.0.0:3000:3000
      - 0.0.0.0:3030:3030
      - 0.0.0.0:8888:8888
    environment:
      - NETWORK_ID=2018
      - NETWORK_NAME=dev
      - LITE=1
      - LITE_DB_PERSIST=0
      - LITE_API_PORT=3030
      - APP_PORT=3000
      - METRICS_PORT=8888
      - DEEPSTREAM_HOST=deepstream
    command: ["./bin/app.js", "-v"]
  deepstream:
    container_name: ethstats-network-deepstream
    image: deepstreamio/deepstream.io:3.2.2
    restart: always
    ports:
      - 0.0.0.0:6020:6020
  dashboard:
    container_name: ethstats-network-dashboard
    image: alethio/ethstats-network-dashboard:latest
    restart: always
    depends_on:
      - server
    volumes:
      - ../../config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 0.0.0.0:8080:80
    environment:
      - NETSTATS_API_URL=http://192.168.42.35:3030
      - DS_URL=192.168.42.35:6020
      - DS_USER=frontend
      - DS_PASS=

I have deployed ethstat client on kubernetes cluster to connect to besu node through ws protocol.
Ethstat client shows that the connection to ethstat server and besu node is successfull and some messages are sent, but nothing is shown in ethstat dashboard.

![image](https://user-images.githubusercontent.com/59224403/115881451-ffc75000-a460-11eb-9c08-8fbb8c685c40.png)

![image](https://user-images.githubusercontent.com/59224403/115881670-39985680-a461-11eb-99ec-2246d3a6b346.png)

![image](https://user-images.githubusercontent.com/59224403/115881688-3f8e3780-a461-11eb-8550-db012efae82f.png)

this options is set to run for ethstat client:
--net host --register --account-email test@test.com --node-name node-0 --server-url http://the node public ip in which ethstat server is installed:3000/ --client-url ws://10.43.22.227:8546

The network Id is shown in genesis config file but I can't find network name in genesis.

**Comment by mohjam2004** [comment]
The time setting between alethio ethstat client and server was not the same. I fixed it and docker-compose down/up, but the dashboard doesn't show any data.

**Comment by mohjam2004** [comment]
I also changed all 0.0.0.0 IPs to the correct server IP. But it doesn't solve the issue.

**Comment by mohjam2004** [comment]
This is Ethstat server logs. I shows the messages are being received from besu node:

![image](https://user-images.githubusercontent.com/59224403/115950015-f2a47280-a4ed-11eb-97d0-4e75815577b2.png)

**Comment by mohjam2004** [comment]
I also changed command option in ethstat client (client-url: ) to use http protocol instead of ws, but no data still is shown in dashboard.

![image](https://user-images.githubusercontent.com/59224403/115952329-8845ff00-a4fa-11eb-9e50-39211310432a.png)

**Comment by mohjam2004** [comment]
**This is json-rpc and ws configuration on besu nodes:**
Is there something wrong here?

# Every possible CLI should be in this file.
#
# Please use a plausible value, besu has to at least be able to parse it.
# If it is a multi-valued CLI make it a TOML array.
# If it is a number or boolean make it a number or boolean
# All other config options are strings, and must be quoted.

# Node Information
data-path="/data"
genesis-file="/etc/genesis/genesis.json"
# TODO : insert as command line & mount Volume
# rpc-http-authentication-credentials-file="none"
# TODO : insert as command line & mount Volume
# rpc-ws-authentication-credentials-file="none"
# TODO : insert as command line & mount Volume
# permissions-nodes-config-file="./permissions_config.toml"
# TODO : insert as command line & mount Volume
# permissions-accounts-config-file="./permissions_config.toml"
logging="INFO"

# Transaction Pool
tx-pool-retention-hours=999
tx-pool-max-size=1024

# P2P network
p2p-enabled=true
discovery-enabled=true
#p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25

host-allowlist=["*"]

# JSON-RPC
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]
rpc-http-cors-origins=["*"]
rpc-http-authentication-enabled=false

# GRAPHQL-RPC
graphql-http-enabled=false
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]
rpc-ws-authentication-enabled=false

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

**Comment by mohjam2004** [comment]
The ethstat server stack is installed in one host. The installed version is as followed:

![image](https://user-images.githubusercontent.com/59224403/115955626-f8f61700-a50c-11eb-808e-c14350e8ed3b.png)

**Comment by mohjam2004** [comment]
I also add some environment variable in docker compose yaml file:

![image](https://user-images.githubusercontent.com/59224403/115955674-3eb2df80-a50d-11eb-905b-fdfe753aadd8.png)

![image](https://user-images.githubusercontent.com/59224403/115955712-80dc2100-a50d-11eb-970f-aa46f9bbed71.png)

**Comment by mohjam2004** [comment]
Hello again @valer-cara @baxy @evanstucker-hates-2fa 
Any idea about this issue?
Regards

**Comment by valer-cara** [comment]
Hey @mohjam2004, thanks for the detailed documentation on this issue!
Unfortunately, Alethio is no longer operating so the whole software stack offered here is no longer maintained. Sorry for the headache!
